#!/bin/sh

echo "Ar jus sutinkate? [yes arba no]: " 
read yno
case $yno in

        [yY] | [yY][Ee][Ss] )
                echo "Sutinku" 
                ;;
        [nN] | [nN][Oo] )
                echo "Nesutinkate, todel negalite testi";
                exit 1
                ;;
        *) echo "Blogi duomenys" 
           exit 255
           ;;
esac
