#!/bin/sh
if [ $# -eq 0 ] ;
then
    echo "Programa paleista be argumentu"
    exit 1
else
    echo "Argumentu skaicius: $#"
    echo "Argumentu sarasas: $*"
fi
if [ $# -eq 1 ] ;
then 
   if [ -d $1 ] ;
   then
      cd $1
      for i in * ;
      do
      echo $i
      done
     fi
fi
