#!/bin/sh
par1=$1
par2=$2
if test ! $# -eq 2 ;
then
    echo "Blogas argumentu kiekis!"  
  elif test ! -f $1   
    then
    echo "Pirmas parametras nera failas"
      elif test ! -f $2
        then
        echo "Antras parametras nera failas"
      else 
         set `ls -l $par1 | awk '{print $3}`
         var1=$1
         set `ls -l $par2 | awk '{print $3}`
         var2=$1
fi
     if [ "$var2" = "$var1" ] ;
     then
         echo "Savininkai sutampa"
         exit 0
     else
         echo "Skiriasi savininkai"
         exit 1
fi
 
   
